//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplyNew.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ApplyNew.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted formats are .jpg, .jpeg, .doc, .docx, .pdf, .gif, .png.
        /// </summary>
        public static string Acceptedformat_docuploads {
            get {
                return ResourceManager.GetString("Acceptedformat_docuploads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I understand and agree that I must provide original versions of all relevant attestations and equivalency documentation within my first semester at Canadian University Dubai.
        /// </summary>
        public static string Agree_condtion1 {
            get {
                return ResourceManager.GetString("Agree_condtion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I certify that the information I have provided in this application is true and complete. I fully realize that omission or falsification of information will be sufficient reason for rejection and dismissal.
        /// </summary>
        public static string Agree_condtion2 {
            get {
                return ResourceManager.GetString("Agree_condtion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application fee payment does not guarantee acceptance in Canadian University Dubai and is non-refundable. Tuition deposit/ Seat reservation fees of AED 2,500.00/- is non-refundable..
        /// </summary>
        public static string Agree_condtion3 {
            get {
                return ResourceManager.GetString("Agree_condtion3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Paid.
        /// </summary>
        public static string Amount_Paid_cudreceipt {
            get {
                return ResourceManager.GetString("Amount_Paid_cudreceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Payable.
        /// </summary>
        public static string AmountPayable {
            get {
                return ResourceManager.GetString("AmountPayable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant Basic Information.
        /// </summary>
        public static string ApplicantBasicInfo {
            get {
                return ResourceManager.GetString("ApplicantBasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant Information.
        /// </summary>
        public static string Applicantinfoh1 {
            get {
                return ResourceManager.GetString("Applicantinfoh1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant Type.
        /// </summary>
        public static string ApplicantType {
            get {
                return ResourceManager.GetString("ApplicantType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am applying for.
        /// </summary>
        public static string Applyfor {
            get {
                return ResourceManager.GetString("Applyfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aunt.
        /// </summary>
        public static string Aunt {
            get {
                return ResourceManager.GetString("Aunt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bachelors.
        /// </summary>
        public static string Bachelors {
            get {
                return ResourceManager.GetString("Bachelors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to application.
        /// </summary>
        public static string Back_to_application {
            get {
                return ResourceManager.GetString("Back_to_application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brother.
        /// </summary>
        public static string brother {
            get {
                return ResourceManager.GetString("brother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a Relation.
        /// </summary>
        public static string Choose_a_relation {
            get {
                return ResourceManager.GetString("Choose_a_relation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to College/University Information.
        /// </summary>
        public static string College_University_Information {
            get {
                return ResourceManager.GetString("College_University_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue an existing Application.
        /// </summary>
        public static string Continue_an_existing_Application {
            get {
                return ResourceManager.GetString("Continue_an_existing_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue to make Payment.
        /// </summary>
        public static string Continue_to_make_Payment {
            get {
                return ResourceManager.GetString("Continue_to_make_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new Application.
        /// </summary>
        public static string Create_a_new_Application {
            get {
                return ResourceManager.GetString("Create_a_new_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Address.
        /// </summary>
        public static string CurrentAddress {
            get {
                return ResourceManager.GetString("CurrentAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string dob {
            get {
                return ResourceManager.GetString("dob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents Uploads.
        /// </summary>
        public static string DocumentsUploads {
            get {
                return ResourceManager.GetString("DocumentsUploads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education and Documents.
        /// </summary>
        public static string Eanddoc {
            get {
                return ResourceManager.GetString("Eanddoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education Info.
        /// </summary>
        public static string Education_Info {
            get {
                return ResourceManager.GetString("Education_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education Information.
        /// </summary>
        public static string EducationInfo {
            get {
                return ResourceManager.GetString("EducationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Language Requirement.
        /// </summary>
        public static string ELR {
            get {
                return ResourceManager.GetString("ELR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email ID.
        /// </summary>
        public static string Email_ID_cudreceipt {
            get {
                return ResourceManager.GetString("Email_ID_cudreceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email_Onlinepayment {
            get {
                return ResourceManager.GetString("Email_Onlinepayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employer Details.
        /// </summary>
        public static string Employer_Details {
            get {
                return ResourceManager.GetString("Employer_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter College Name.
        /// </summary>
        public static string Enter_College_Name {
            get {
                return ResourceManager.GetString("Enter_College_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter School Name.
        /// </summary>
        public static string Enter_School_Name {
            get {
                return ResourceManager.GetString("Enter_School_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your Email ID.
        /// </summary>
        public static string Enter_Your_EmailID {
            get {
                return ResourceManager.GetString("Enter_Your_EmailID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your Applicant ID.
        /// </summary>
        public static string Enter_Your_ProspectID {
            get {
                return ResourceManager.GetString("Enter_Your_ProspectID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry Date.
        /// </summary>
        public static string Expiry_Date {
            get {
                return ResourceManager.GetString("Expiry_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father.
        /// </summary>
        public static string Father {
            get {
                return ResourceManager.GetString("Father", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank You for submitting your application to canadian university Dubai.
        /// </summary>
        public static string Feedback_msg1_leadcomplete {
            get {
                return ResourceManager.GetString("Feedback_msg1_leadcomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should expect a response back from the admission team within 24 hours.
        /// </summary>
        public static string Feedback_msg2_leadcomplete {
            get {
                return ResourceManager.GetString("Feedback_msg2_leadcomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have any question you may reach us by phone 04-321-9090 or by email at.
        /// </summary>
        public static string Feedback_msg3_leadcomplete {
            get {
                return ResourceManager.GetString("Feedback_msg3_leadcomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name (English).
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name Arabic.
        /// </summary>
        public static string FirstNamearabic {
            get {
                return ResourceManager.GetString("FirstNamearabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPA.
        /// </summary>
        public static string GPA_Collegesection {
            get {
                return ResourceManager.GetString("GPA_Collegesection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPA out of.
        /// </summary>
        public static string GPA_out_of_Collegesection {
            get {
                return ResourceManager.GetString("GPA_out_of_Collegesection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardian.
        /// </summary>
        public static string Guardian {
            get {
                return ResourceManager.GetString("Guardian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string GuardianEmail {
            get {
                return ResourceManager.GetString("GuardianEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string GuardianFirstName {
            get {
                return ResourceManager.GetString("GuardianFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardian Information.
        /// </summary>
        public static string GuardianInfo {
            get {
                return ResourceManager.GetString("GuardianInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string GuardianLastName {
            get {
                return ResourceManager.GetString("GuardianLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string GuardianPhone {
            get {
                return ResourceManager.GetString("GuardianPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship.
        /// </summary>
        public static string GuardianRelationship {
            get {
                return ResourceManager.GetString("GuardianRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark (*) is required for completion.
        /// </summary>
        public static string Guardianrequiredforcompletion {
            get {
                return ResourceManager.GetString("Guardianrequiredforcompletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How did you hear about us?.
        /// </summary>
        public static string hearabtus {
            get {
                return ResourceManager.GetString("hearabtus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select High School country.
        /// </summary>
        public static string HighSchoolcountry {
            get {
                return ResourceManager.GetString("HighSchoolcountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High School Information.
        /// </summary>
        public static string HighSchoolInfo {
            get {
                return ResourceManager.GetString("HighSchoolInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you require housing accommodation?.
        /// </summary>
        public static string housingaccommodation {
            get {
                return ResourceManager.GetString("housingaccommodation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the institution you are transferring from.
        /// </summary>
        public static string institution_you_are_transferring_from {
            get {
                return ResourceManager.GetString("institution_you_are_transferring_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name (English).
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name Arabic.
        /// </summary>
        public static string LastNamearabic {
            get {
                return ResourceManager.GetString("LastNamearabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide all responses in English.
        /// </summary>
        public static string list1 {
            get {
                return ResourceManager.GetString("list1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required fields are indicated by a red asterisk (*).
        /// </summary>
        public static string list2 {
            get {
                return ResourceManager.GetString("list2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masters.
        /// </summary>
        public static string Masters {
            get {
                return ResourceManager.GetString("Masters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will be processing your application and contacting you as needed..
        /// </summary>
        public static string Message1_cudreceipt {
            get {
                return ResourceManager.GetString("Message1_cudreceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following information is for your records. For your convenience, we have emailed you this information..
        /// </summary>
        public static string Message2_cudreceipt {
            get {
                return ResourceManager.GetString("Message2_cudreceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name (English).
        /// </summary>
        public static string MiddleName {
            get {
                return ResourceManager.GetString("MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name Arabic.
        /// </summary>
        public static string MiddleNamearabic {
            get {
                return ResourceManager.GetString("MiddleNamearabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother.
        /// </summary>
        public static string Mother {
            get {
                return ResourceManager.GetString("Mother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name_cudreceipt {
            get {
                return ResourceManager.GetString("Name_cudreceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you need a student visa?.
        /// </summary>
        public static string needastudentvisa {
            get {
                return ResourceManager.GetString("needastudentvisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you need transportation?.
        /// </summary>
        public static string Needtransportation {
            get {
                return ResourceManager.GetString("Needtransportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Application.
        /// </summary>
        public static string Official_CUD_Online_Application {
            get {
                return ResourceManager.GetString("Official_CUD_Online_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Application.
        /// </summary>
        public static string Online_Application {
            get {
                return ResourceManager.GetString("Online_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Application.
        /// </summary>
        public static string Online_Application_cudreceipt {
            get {
                return ResourceManager.GetString("Online_Application_cudreceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Payment Page.
        /// </summary>
        public static string Online_Payment_Page {
            get {
                return ResourceManager.GetString("Online_Payment_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional Information.
        /// </summary>
        public static string OptionalInformation {
            get {
                return ResourceManager.GetString("OptionalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuition or Other Miscellaneous fees.
        /// </summary>
        public static string Other_Miscellaneous_fees {
            get {
                return ResourceManager.GetString("Other_Miscellaneous_fees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Details.
        /// </summary>
        public static string Payment_Details {
            get {
                return ResourceManager.GetString("Payment_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone 1.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please continue your appliction by clicking in the below button..
        /// </summary>
        public static string Please_continue_your_appliction {
            get {
                return ResourceManager.GetString("Please_continue_your_appliction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the below data to retrieve your application.
        /// </summary>
        public static string Please_enter_the_below_data_to_retreieve_profile_info {
            get {
                return ResourceManager.GetString("Please_enter_the_below_data_to_retreieve_profile_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide your bachelor information.
        /// </summary>
        public static string Please_provide_your_bachelor_information {
            get {
                return ResourceManager.GetString("Please_provide_your_bachelor_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify your special needs.
        /// </summary>
        public static string Please_specify_your_special_needs {
            get {
                return ResourceManager.GetString("Please_specify_your_special_needs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed for Payment.
        /// </summary>
        public static string Proceed_for_Payment {
            get {
                return ResourceManager.GetString("Proceed_for_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Choice.
        /// </summary>
        public static string Program {
            get {
                return ResourceManager.GetString("Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProspectID.
        /// </summary>
        public static string ProspectID_cudreceipt {
            get {
                return ResourceManager.GetString("ProspectID_cudreceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark (*) is required for completion.
        /// </summary>
        public static string Required_for_docuploads {
            get {
                return ResourceManager.GetString("Required_for_docuploads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I would like to reserve my seat for 2500 AED.
        /// </summary>
        public static string reserve_my_seat {
            get {
                return ResourceManager.GetString("reserve_my_seat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve Application.
        /// </summary>
        public static string Retrieve_Application {
            get {
                return ResourceManager.GetString("Retrieve_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Exit.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string Score_HSsection {
            get {
                return ResourceManager.GetString("Score_HSsection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score out of.
        /// </summary>
        public static string Score_out_of_HSsection {
            get {
                return ResourceManager.GetString("Score_out_of_HSsection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select College.
        /// </summary>
        public static string Select_College_Collegesection {
            get {
                return ResourceManager.GetString("Select_College_Collegesection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select College country.
        /// </summary>
        public static string Select_College_country_Collegesection {
            get {
                return ResourceManager.GetString("Select_College_country_Collegesection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select curriculum type.
        /// </summary>
        public static string Select_curriculum_type_HSsection {
            get {
                return ResourceManager.GetString("Select_curriculum_type_HSsection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select High School.
        /// </summary>
        public static string Select_High_School {
            get {
                return ResourceManager.GetString("Select_High_School", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Country.
        /// </summary>
        public static string SelectCountry {
            get {
                return ResourceManager.GetString("SelectCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sister.
        /// </summary>
        public static string sister {
            get {
                return ResourceManager.GetString("sister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have any special needs? This information is voluntary and confidential.
        /// </summary>
        public static string Specialneeds {
            get {
                return ResourceManager.GetString("Specialneeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Application.
        /// </summary>
        public static string Start_Application {
            get {
                return ResourceManager.GetString("Start_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Name.
        /// </summary>
        public static string Student_Name {
            get {
                return ResourceManager.GetString("Student_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success! Your application has been submitted..
        /// </summary>
        public static string Successful_msg_cudreceipt {
            get {
                return ResourceManager.GetString("Successful_msg_cudreceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You had successfully created an account. A detailed Email has been send to your registered Email about the account details..
        /// </summary>
        public static string Successful_registration_message {
            get {
                return ResourceManager.GetString("Successful_registration_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Entrance Term.
        /// </summary>
        public static string term {
            get {
                return ResourceManager.GetString("term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Date.
        /// </summary>
        public static string TestDate {
            get {
                return ResourceManager.GetString("TestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Score.
        /// </summary>
        public static string TestScore {
            get {
                return ResourceManager.GetString("TestScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Selection.
        /// </summary>
        public static string TestSelection {
            get {
                return ResourceManager.GetString("TestSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank You for registering with canadian university Dubai!.
        /// </summary>
        public static string Thank_You_for_registering_with_canadian_university_Dubai {
            get {
                return ResourceManager.GetString("Thank_You_for_registering_with_canadian_university_Dubai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Date.
        /// </summary>
        public static string Transaction_Date_cudreceipt {
            get {
                return ResourceManager.GetString("Transaction_Date_cudreceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction number.
        /// </summary>
        public static string Transaction_num_cudreceipt {
            get {
                return ResourceManager.GetString("Transaction_num_cudreceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Institution Country.
        /// </summary>
        public static string Transfer_Institution_Country {
            get {
                return ResourceManager.GetString("Transfer_Institution_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Program.
        /// </summary>
        public static string Transfer_Program {
            get {
                return ResourceManager.GetString("Transfer_Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Information.
        /// </summary>
        public static string TransferInfo {
            get {
                return ResourceManager.GetString("TransferInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Institution.
        /// </summary>
        public static string TransferInstitution {
            get {
                return ResourceManager.GetString("TransferInstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you transferring from another Institution.
        /// </summary>
        public static string Transferstatus {
            get {
                return ResourceManager.GetString("Transferstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you plan on transferring or completing your studies in a partner university / college in Canada?.
        /// </summary>
        public static string Transfertocanada {
            get {
                return ResourceManager.GetString("Transfertocanada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UAE ID.
        /// </summary>
        public static string UAE_ID {
            get {
                return ResourceManager.GetString("UAE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UAE Residency Status.
        /// </summary>
        public static string UAEresidencystatus {
            get {
                return ResourceManager.GetString("UAEresidencystatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UAE Resident.
        /// </summary>
        public static string UAEresident {
            get {
                return ResourceManager.GetString("UAEresident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncle.
        /// </summary>
        public static string Uncle {
            get {
                return ResourceManager.GetString("Uncle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, Your Payment Was Unsuccessful.Please Try Again..
        /// </summary>
        public static string Unsuccessful_msg_cudreceipt {
            get {
                return ResourceManager.GetString("Unsuccessful_msg_cudreceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Personal Information.
        /// </summary>
        public static string Update_Personal_Information {
            get {
                return ResourceManager.GetString("Update_Personal_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload single documents at a time.
        /// </summary>
        public static string Uploadsingledoc_docuuploads {
            get {
                return ResourceManager.GetString("Uploadsingledoc_docuuploads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Email.
        /// </summary>
        public static string vemail {
            get {
                return ResourceManager.GetString("vemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Canadian University Dubai!.
        /// </summary>
        public static string Welcome_sc1 {
            get {
                return ResourceManager.GetString("Welcome_sc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you ready to apply to Canadian University Dubai (CUD)? Begin your educational journey by completing our simple 3 step application..
        /// </summary>
        public static string WelcomeMessage1_sc1 {
            get {
                return ResourceManager.GetString("WelcomeMessage1_sc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow along the application to apply to one of our undergraduate or graduate programs. To begin a new application, kindly click the &apos;Create A New Application&apos; button below. If you have already started an application, but the application is incomplete, kindly proceed by clicking the &apos;Continue An Existing Application&apos; button..
        /// </summary>
        public static string WelcomeMessage2_sc1 {
            get {
                return ResourceManager.GetString("WelcomeMessage2_sc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1: Applicant Information.
        /// </summary>
        public static string WelcomeMessage3_sc1 {
            get {
                return ResourceManager.GetString("WelcomeMessage3_sc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 2: Education Information &amp; Documentation.
        /// </summary>
        public static string WelcomeMessage4_sc1 {
            get {
                return ResourceManager.GetString("WelcomeMessage4_sc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 3: Application Payment.
        /// </summary>
        public static string WelcomeMessage5_sc1 {
            get {
                return ResourceManager.GetString("WelcomeMessage5_sc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you require any assistance with your application or are facing technical difficulty, kindly contact.
        /// </summary>
        public static string WelcomeMessage6_sc1 {
            get {
                return ResourceManager.GetString("WelcomeMessage6_sc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your interest in CUD, we look forward to connecting with you!.
        /// </summary>
        public static string WelcomeMessage7_sc1 {
            get {
                return ResourceManager.GetString("WelcomeMessage7_sc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can access your submitted application here.
        /// </summary>
        public static string You_can_access_your_submitted_application_here {
            get {
                return ResourceManager.GetString("You_can_access_your_submitted_application_here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may reach us by phone at.
        /// </summary>
        public static string You_may_reach_us_cudreceipt {
            get {
                return ResourceManager.GetString("You_may_reach_us_cudreceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Application.
        /// </summary>
        public static string Your_Application {
            get {
                return ResourceManager.GetString("Your_Application", resourceCulture);
            }
        }
    }
}
