//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplyNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class Custom_DoctNametable
    {
        public long ID { get; set; }
        public Nullable<int> DocNameID { get; set; }
        public string DocName { get; set; }
        public string DegreeType { get; set; }
        public string TransferType { get; set; }
        public List<Custom_DoctNametable> DocNamelst { get; set; }
    }
}
