//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplyNew
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CAMS_ProfileProgressEntities : DbContext
    {
        public CAMS_ProfileProgressEntities()
            : base("name=CAMS_ProfileProgressEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<Custom_Profileprogress_Result> Custom_Profileprogress(string prospectid)
        {
            var prospectidParameter = prospectid != null ?
                new ObjectParameter("prospectid", prospectid) :
                new ObjectParameter("prospectid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Custom_Profileprogress_Result>("Custom_Profileprogress", prospectidParameter);
        }
    }
}
