//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplyNew
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CAMS_TestScoresEntities : DbContext
    {
        public CAMS_TestScoresEntities()
            : base("name=CAMS_TestScoresEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<MathApptestscores_Result> MathApptestscores(string studentid)
        {
            var studentidParameter = studentid != null ?
                new ObjectParameter("studentid", studentid) :
                new ObjectParameter("studentid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MathApptestscores_Result>("MathApptestscores", studentidParameter);
        }
    }
}
